### ISSUE TITLE
I got a error when using plotting module

### ISSUE THREAD

**Issue by lannistercaer** [jakobrunge/tigramite#125]
![d28dae5becb091eec7ce49b4b9eb242](https://user-images.githubusercontent.com/66576949/122523722-e9490980-d049-11eb-8b7f-fdc3c6ac40aa.png)

**Comment by sagarsimha** [comment]
@lannistercaer Please upgrade matplotlib>=3.4.0. The recommended versions for all packages are mentioned on the Readme.

**Comment by lannistercaer** [comment]
> @lannistercaer Please upgrade matplotlib>=3.4.0. The recommended versions for all packages are mentioned on the Readme.

thank you very much! the issue has been solved

**Comment by zlf123-cup** [comment]
Hello, thank you very much for your contribution. How to upgrade matplotlib3.4.3 with anaconda

**Comment by AviralKumarTiwari** [comment]
> > @lannistercaer Please upgrade matplotlib>=3.4.0. The recommended versions for all packages are mentioned on the Readme.
> 
> thank you very much! the issue has been solved but i have new errors now:

pcmci.print_significant_links(
        p_matrix = results['p_matrix'], 
        q_matrix = q_matrix,
        val_matrix = results['val_matrix'],
        alpha_level = 0.01)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
C:\Users\Public\Documents\iSkysoft\CreatorTemp/ipykernel_10748/2856702272.py in <module>
----> 1 pcmci.print_significant_links(
      2         p_matrix = results['p_matrix'],
      3         q_matrix = q_matrix,
      4         val_matrix = results['val_matrix'],
      5         alpha_level = 0.01)

TypeError: print_significant_links() got an unexpected keyword argument 'q_matrix'


link_matrix = pcmci.return_significant_links(pq_matrix=q_matrix,
                        val_matrix=results['val_matrix'], alpha_level=0.01)['link_matrix']


return_significant_links() is DEPRECATED: now run_pcmci(),  run_mci() and all variants directly return the graph based on thresholding the p_matrix at alpha_level. The graph can also be updated based on a (potentially further adjusted) p_matrix using get_graph_from_pmatrix(). A dictionary of parents can be obtained with return_parents_dict().
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
C:\Users\Public\Documents\iSkysoft\CreatorTemp/ipykernel_10748/1288781391.py in <module>
----> 1 link_matrix = pcmci.return_significant_links(pq_matrix=q_matrix,
      2                         val_matrix=results['val_matrix'], alpha_level=0.01)['link_matrix']

TypeError: 'NoneType' object is not subscriptable

**Comment by sagarsimha** [comment]
I think you are referring to the tutorials of an older version with the code base of a relatively newer version. I would suggest to clone the latest version, 5.0 and use the respective tutorials therein. The warning above is one of the changes updated - link_matrix is now replaced by graph object.

**Comment by BeckyChanZC** [comment]
I am having the same problem, even though I have upgraded matplotlib, it still shows 'Polygon' object has no attribute 'clear'. I also changed the code as required by the latest version 5.0. Why is there still a problem? Thank you very much.
